; asciiart Racket (racket 7.0)
(define (mandel i a b ca cb)
    (define an (+ (- (* a a) (* b b)) ca))
    (define bn (+ (* 2 a b) cb))
    (if (= i 16)
        (display " ")
        (if (> (+ (* an an) (* bn bn)) 4)
            (display (string-upcase (format "~X" i)))
            (mandel (+ i 1) an bn ca cb)
        )
    )
)
(for ([y (in-range -12 13)])
    (for ([x (in-range -39 40)])
        (define ca (* x 0.0458))
        (define cb (* y 0.08333))
        (mandel 0 ca cb ca cb)
    )
    (newline)
)
